### ISSUE TITLE
BallTracker' object has no attribute 'perform_init_ops'

### ISSUE THREAD

**Issue by huynpase** [dcrblack/snooker-ball-tracker#2]
Hi team,

I'm trying to run your code to detect ball in images but get the error below.
Traceback (most recent call last):
  File "ball_tracker_cli.py", line 273, in <module>
    _, _, hsv = ball_tracker.perform_init_ops(frame, width=args.width, morph=args.morph, crop=args.crop)
AttributeError: 'BallTracker' object has no attribute 'perform_init_ops'

Could you tell me what i did wrong? Thank you very much!

**Comment by Danthewaann** [comment]
Hi @huynpase, Are you running the `ball_tracker_cli.py` script directly and from what branch? Unfortunately at the moment that script isn't up to date for now. I'll try to do some work on that script this weekend to get it working again.

**Comment by huynpase** [comment]
Hi @dcrblack  thank for you respond :D 
I'm running ball_tracker_cli from both 2 branch but not work!
I'm waitting for your script <3 
Thank you so much!

**Comment by Danthewaann** [comment]
@huynpase I've just committed a fix (8fa8232) for the `ball_tracker_cli.py` script into the `pyqt-update` branch. let me know if the fix works for you.

**Comment by huynpase** [comment]
Thank for your commit!
It work very well!
